#pragma once

#include "driver/gpio.h"
#include "driver/ledc.h"

enum {
    BOARD_PIN_START_BUTTON = GPIO_NUM_0,
    BOARD_PIN_US_TRIG = GPIO_NUM_6,
    BOARD_PIN_MOTOR_ENABLE = GPIO_NUM_7,
    BOARD_PIN_ENCODER_A_B = GPIO_NUM_8,
    BOARD_PIN_MOTOR_A_PWM = GPIO_NUM_9,
    BOARD_PIN_MOTOR_A_IN1 = GPIO_NUM_10,
    BOARD_PIN_MOTOR_A_IN2 = GPIO_NUM_11,
    BOARD_PIN_MOTOR_B_PWM = GPIO_NUM_12,
    BOARD_PIN_US_ECHO = GPIO_NUM_13,
    BOARD_PIN_MOTOR_B_IN1 = GPIO_NUM_14,
    BOARD_PIN_MOTOR_B_IN2 = GPIO_NUM_15,
    BOARD_PIN_MOTOR_C_PWM = GPIO_NUM_16,
    BOARD_PIN_MOTOR_C_IN1 = GPIO_NUM_17,
    BOARD_PIN_ENCODER_A_A = GPIO_NUM_18,
    BOARD_PIN_MOTOR_C_IN2 = GPIO_NUM_21,
    /* GPIO19/20 are permanently reserved for the UVC camera USB D-/D+. */
    BOARD_PIN_CAMERA_USB_D_MINUS = GPIO_NUM_19,
    BOARD_PIN_CAMERA_USB_D_PLUS = GPIO_NUM_20,
    /* GPIO5 was released when the four-channel infrared board was removed. */
    BOARD_PIN_DISPLAY_MOSI = GPIO_NUM_5,
    BOARD_PIN_DISPLAY_CS = GPIO_NUM_3,
    BOARD_PIN_DISPLAY_DC = GPIO_NUM_38,
    BOARD_PIN_DISPLAY_SCLK = GPIO_NUM_45,
    BOARD_PIN_DISPLAY_RESET = GPIO_NUM_47,
    BOARD_PIN_ENCODER_B_A = GPIO_NUM_39,
    BOARD_PIN_ENCODER_B_B = GPIO_NUM_40,
    BOARD_PIN_ENCODER_C_A = GPIO_NUM_41,
    BOARD_PIN_ENCODER_C_B = GPIO_NUM_42,
    BOARD_PIN_UART0_TX = GPIO_NUM_43,
    BOARD_PIN_UART0_RX = GPIO_NUM_44,
};
enum {
    BOARD_MOTOR_A_CHANNEL = LEDC_CHANNEL_0,
    BOARD_MOTOR_B_CHANNEL = LEDC_CHANNEL_1,
    BOARD_MOTOR_C_CHANNEL = LEDC_CHANNEL_2,
};
